apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-green-dpm
  namespace: dev-ns
  labels:
    dev/deployed: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      color: green
      dev/deployed: deploy
  template:
    metadata:
      labels:
        color: green
        dev/deployed: deploy
    spec:
      containers:
      - image: IMAGE
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "80Mi"
            cpu: "300m"
        name: dev-green-container
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dev-pv
          mountPath: /aws/static/
      volumes:
      - name: dev-pv
        persistentVolumeClaim:
          claimName: efs-claim
  strategy:
    type: Recreate