apiVersion: v1
kind: Service
metadata:
  name: dev-blue-svc
  namespace: dev-ns
spec:
  selector:
    color: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort