apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-eks-cluster
  version: "1.30"
  region: ap-northeast-2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true

vpc:
  subnets:
    public:
      ap-northeast-2a: { id: public_a }
      ap-northeast-2b: { id: public_b }
      ap-northeast-2c: { id: public_c }
    private:
      ap-northeast-2a: { id: private_a }
      ap-northeast-2b: { id: private_b }
      ap-northeast-2c: { id: private_c }

managedNodeGroups:
  - name: dev-web-ng
    labels: { dev/deployed: deploy }
    instanceName: dev-web-svc
    instanceType: c5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    privateNetworking: true